### PR TITLE
Added Credits in Help menu

### PR DESCRIPTION
**Pull request by nucliweb**
Create credits and added un help menu.

### CODE REVIEW

**Comment by antiboredom** [comment]
Hey - for some reason nothing is happening when I click on that menu item. Can you take a look?

**Comment by nucliweb** [comment]
@antiboredom Ops, fixed ;)

**Comment by nucliweb** [comment]
Hi @antiboredom, @lmccart  what do you think about this PR?

**Comment by antiboredom** [comment]
Apologies for the delay - I'm taking a look at all outstanding pull requests today!

**Comment by nucliweb** [comment]
Great

**Comment by antiboredom** [comment]
@nucliweb I love how it looks!  One issue: I think it's a little confusing how it's modal window that you can't move around, and allows the use to continue editing their document.

A fix for this could either be to make it open in a new window (like what happens if you go to the p5 menu and then click "about"), or to make it completely take over the screen, and then add a "close" button.

let me know what you think - and thanks for doing this!

**Comment by nucliweb** [comment]
We can add an overlay to block the publication or, as you propose, for change to be displayed in a window.

**Comment by antiboredom** [comment]
@nucliweb I'd be fine with either - which do you prefer?

**Comment by nucliweb** [comment]
The overlay would be faster, but I think it'll have more sense open a new window

**Comment by antiboredom** [comment]
agreed, but totally up to you!

**Pull request closed without merging**
