### PR TITLE
Live coding

### PR DESCRIPTION
**Pull request by sepans**
Enables live-coding.

Updates code running in browser when global variables or functions (except setup) change. 

There is a switch <code>var liveCodingEnabled = true;</code> on top of p5-mode.js file which turns off live coding in case it turned out live-coding breaks the editor.

### CODE REVIEW

**Comment by sepans** [comment]
<code>MyObject.prototype.myFunction = function() {}</code> doesn't work.
Most likely because the parser doesn't parse it as a function declaration at top level parse tree.

**Comment by sepans** [comment]
Above issue fixed!

**Comment by sepans** [comment]
One problem I noticed is that p5.js stops when there is an invalid code (valid javascript with runtime errors). what is the best way handle that? resume p5? or catch it before it is set in global context? (not sure later is possible)

**Comment by sepans** [comment]
https://github.com/sepans/p5.js-editor/commit/7d05978f47e0db89ee7678dc381d83770371d812 catches runtime errors before setting the functions to window, but it has side effects: 
For draw function it is fine but for all other functions defined in global scope, running them might unwantedly change the state of the sketch.

**Comment by antiboredom** [comment]
prototype functions seem to break!

**Comment by sepans** [comment]
fixed prototype functions, plus changes in <code>setup()</code>

**Comment by sepans** [comment]
TODO: call setup when functions that are being called within setup (like object constructors) change!

**Comment by sepans** [comment]
This PR has become obsolete. I did the implementation again in a new branch. Will submit PR when done.

**Comment by jtoy** [comment]
what happened to this ? Did this get merged? Is there a new PR ?

**Comment by doxanthropos** [comment]
Probably it was abandoned, because the editor is now depricated and will not see further development in the near future. See the top of the readme at https://github.com/processing/p5.js-editor
It will be replaced by a web editor that is currently in development.

**Comment by jtoy** [comment]
i think worth using for the live code mode, even if the editor is going to be gone. I'll play with it.

**Pull request closed without merging**
