### PR TITLE
Added editorconfig rules

### PR DESCRIPTION
**Pull request by nucliweb**

### CODE REVIEW

**Comment by antiboredom** [comment]
@nucliweb can you explain this a bit?

**Comment by nucliweb** [comment]
Sorry @antiboredom 

With these rules we can ensure consistency in the format of all files.
This can prevent differences in indents, charset, end of line, etc... in the commits and PR

We have plugins for a lot of editors in http://editorconfig.org/

**Comment by antiboredom** [comment]
Ah - I see! So this is for us as developers/contributors rather than as rules for the user-facing side?

**Comment by nucliweb** [comment]
Yes.
Thanks for merge ;)

**Pull request merged**
