### PR TITLE
implementation of jerel's design

### PR DESCRIPTION
**Pull request by lmccart**
This isn't quite ready to go yet... I haven't tested it across browsers or on windows, but I wanted to show you where this is headed and let you test it out. The one remaining piece is styling the searchbox, I'll work on this more later this week. Let me know if you notice any major red flags. There is one question I had which involves strings versus booleans, you can find these places marked "ask sam" :).

### CODE REVIEW

**Comment by lmccart** [comment]
ok i think this is fully ready to go as per the design spec! let me know if you notice any issues.

**Comment by lmccart** [comment]
hey @antiboredom, any chance we can get this and the lib update merged in sometime soonish? i'm happy to go ahead and do it, but i don't know if you want to review first?

**Comment by antiboredom** [comment]
Hey - sorry for the delay. A bit swamped but I'll take a look tomorrow.

**Comment by lmccart** [comment]
closing this. opening PR from master branch.

**Pull request closed without merging**
